sdscli/cloud/aws/asg.py
Rather than filtering on Owner='self', filter on all private images.
This would fix https://github.com/sdskit/sdscli/issues/11
=> Issue 11: Change filter used during describe_images

sdscli/cloud/aws/asg.py
Rather than filtering on Owner='self', filter on all private images.
This would fix https://github.com/sdskit/sdscli/issues/11
=> Change filter used during describe_images

sdscli/cloud/aws/storage.py, sdscli/command_line.py
Per my conversations with @pymonger, it was decided that it is safe to no longer make `.signal.json` the `--suffix` flag value default as SWOT was the only one using this capability initially. If a value does get passed into the `--suffix` flag, it will get passed onto the Lambda via an environment variable named `SIGNAL_FILE_SUFFIX`.
=> HC-103: Update create cloud staging area command to support non-signal file based triggers

sdscli/cloud/aws/storage.py
sdscli was updated to support reading in a new setting in the sds config called `JOB_TYPES` which can be set under the `STAGING_AREA`. This would contain a mapping of job types to a regular expression like so:
```
JOB_TYPES:
L0A_Prime:
PATTERN: '.*APID(1070|1071|1072|1073|1074|1075|1280|1408).*'
QUEUE: job_worker-small
RELEASE: develop
JOB_TYPE: INGEST_STAGED
JOB_QUEUE: job_worker-small
JOB_RELEASE: develop
```
Note that `JOB_TYPES` is an optional parameter. If it is not specified, sdscli will work the way it normally works. If this parameter is specified, then the lambda will set the appropriate job type that matches the data file in the job type mapping. If nothing matches, then it will set the job type to the default, which is specified in the `JOB_TYPE` setting.
=> HC-104: Updated to support a mapping of job types to regexes for ingest lambda

sdscli/adapters/__init__.py
Restore sds configuration tool:
```
(mozart) ops@localhost:~$ ls -al ~/.sds
ls: cannot access /home/ops/.sds: No such file or directory
(mozart) ops@localhost:~$ sds configure
Traceback (most recent call last):
File "/home/ops/mozart/bin/sds", line 11, in <module>
load_entry_point('sdscli', 'console_scripts', 'sds')()
File "/home/ops/mozart/ops/sdscli/sdscli/command_line.py", line 546, in main
return dispatch(args)
File "/home/ops/mozart/ops/sdscli/sdscli/command_line.py", line 235, in dispatch
return args.func(args)
File "/home/ops/mozart/ops/sdscli/sdscli/command_line.py", line 60, in configure
func = get_adapter_func(sds_type, 'configure', 'configure')
File "/home/ops/mozart/ops/sdscli/sdscli/command_line.py", line 31, in get_adapter_func
return get_func(adapter_mod, func_name)
File …
```
=> restore configuration tool

sdscli/__init__.py, sdscli/adapters/__init__.py, sdscli/adapters/hysds/pkg.py, sdscli/adapters/hysds/rules.py
https://hysds-core.atlassian.net/browse/HC-199
- refactoring `hysds_common`'s `ElasticsearchUtility` to allow for more flexibility
- re-using hysds core's elasticsearch connection because it allows us to read/write to AWS elasticsearch (defined in `.sds/config` and `celeryconfig.py`)
- `lightweight-jobs` will use hysds-core's ES connection
https://github.com/hysds/hysds_commons/pull/26/files#diff-0177d5302571ecb822b51229be69453d
tested `on-demand` and `user_rules` processing in both tosca and figaro
=> refactored es code to reflect changes to ElasticsearchUtility

sdscli/adapters/hysds/pkg.py, sdscli/adapters/hysds/rules.py
fixed import error
```
module.common.aws_instance.mozart (remote-exec): [2020-05-06 17:58:45,477: DEBUG/sdscli/dispatch] args: Namespace(debug=True, file='container-hysds_lightweight-jobs-v1.0.1.sdspkg.tar', func=<function pkg at 0x7f3f819bec20>, subparser='import', type='hysds')
module.common.aws_instance.mozart (remote-exec): [2020-05-06 17:58:45,522: DEBUG/sdscli/pkg] got to pkg(): Namespace(debug=True, file='container-hysds_lightweight-jobs-v1.0.1.sdspkg.tar', func=<function pkg at 0x7f3f819bec20>, subparser='import', type='hysds')
module.common.aws_instance.mozart (remote-exec): [2020-05-06 17:58:45,522: DEBUG/sdscli/pkg] sds_type: hysds
module.common.aws_instance.mozart (remote-exec): [2020-05-06 17:58:45,523: DEBUG/sdscli/__init__] file: /export/home/****/.sds/config …
```
=> fixed es util import

sdscli/adapters/hysds/pkg.py
```
$ sds pkg rm container-iems-sds_nisar-pcm:nsds-689
[2020-05-19 00:56:49,906: ERROR/hysds.log_utils/get_by_id] get() got an unexpected keyword argument 'safe'
Traceback (most recent call last):
File "/export/home/hysdsops/mozart/ops/hysds_commons/hysds_commons/elasticsearch_utils.py", line 55, in get_by_id
data = self.es.get(**kwargs)
File "/export/home/hysdsops/mozart/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
return func(*args, params=params, headers=headers, **kwargs)
TypeError: get() got an unexpected keyword argument 'safe'
Traceback (most recent call last):
File "/export/home/hysdsops/mozart/bin/sds", line 11, in <module>
load_entry_point('sdscli', 'console_scripts', 'sds')()
File "/export/home/hysdsops/mozart/ops/sdscli/sdscli/command_line.py …
```
=> ignore=404 to sds pkg rm

sdscli/__init__.py, sdscli/adapters/hysds/rules.py
after importing rules
```
$ cd ~/.sds/files/test
$ ./import_rules-mozart.sh
[2020-05-25 17:20:58,982: DEBUG/sdscli/dispatch] args: Namespace(debug=True, file='/tmp/user_rules.json.6953', func=<function rules at 0x7f6d3eb39cb0>, subparser='import', type='hysds')
[2020-05-25 17:20:58,983: DEBUG/sdscli/rules] got to pkg(): Namespace(debug=True, file='/tmp/user_rules.json.6953', func=<function rules at 0x7f6d3eb39cb0>, subparser='import', type='hysds')
[2020-05-25 17:20:58,983: DEBUG/sdscli/rules] sds_type: hysds
[2020-05-25 17:20:58,983: DEBUG/sdscli/__init__] file: /export/home/hysdsops/.sds/config
[2020-05-25 17:20:59,325: DEBUG/sdscli/get_func] mod: <module 'sdscli.adapters.hysds.rules' from '/export/home/hysdsops/mozart/ops/sdscli/sdscli/adapters/hysds/rules.py'>
[2020-05-25 …
```
=> added timestamp for missing timestamps when importing rules, bump version

sdscli/adapters/hysds/fabfile.py, sdscli/adapters/hysds/files/jvm.options, sdscli/adapters/hysds/update.py
Currently, the logstash `jvm.options` file has the heap size setting hard-coded to 8GB. This will cause logstash to fail in cases where the instance has less than 8GB of RAM.
This PR updates the provisioning of the logstash `jvm.options` file to metrics and mozart components so that:
- the RAM size of the instance is detected
- if half of this RAM size is greater than 8GB, then the logstash heap size will be set to 8GB
- otherwise, we set the logstash heap size to half of the RAM size
- heap size determination is guided by the documentation at https://www.elastic.co/guide/en/logstash/7.x/jvm-settings.html
This feature was manually tested and verified on a NISAR dev cluster:
- mozart
```
$ sds -d update mozart -f
...
[xxx.xxx.xxx.xxx] Executing task 'send_logstash_jvm_options' …
```
=> HC-287: Make heap settings in the jvm.options file configurable

sdscli/__init__.py, sdscli/adapters/hysds/fabfile.py, sdscli/adapters/hysds/files/run_docker_registry.sh, sdscli/adapters/hysds/files/run_sdswatch_client.sh, sdscli/adapters/hysds/update.py
This PR primarily provisions the mozart, metrics and grq PCM components with the SDSWatch client configuration file (see https://github.com/hysds/hysds/pull/100) and `run_sdswatch_client.sh` script (added to the `send_shipper_conf` fabric function).
Additionally:
- both the `run_sdswatch_client.sh` and `run_docker_registry.sh` scripts have been generalized so that they can run on any of the PCM components: mozart, metrics, grq, factotum, and verdi
- a new fabric function, `send_hysds_scripts`, was added to provision the `run_docker_registry.sh` to the virtualenv bin directory of each component; this function can be extended in the future to provision additional scripts
-  the `run_sdswatch_client.sh` script was updated to disable X-Pack monitoring; otherwise errors trying to reach the …
=> HC-273: provision SDSWatch client on PCM components: mozart, metrics, and grq

sdscli/adapters/hysds/fabfile.py, sdscli/adapters/hysds/files/kibana_dashboard_import/sdswatch-dashboards-old.json, sdscli/adapters/hysds/files/kibana_dashboard_import/sdswatch-dashboards.json, sdscli/adapters/hysds/files/watch_supervisord_services.py, sdscli/adapters/hysds/files/watch_systemd_services.py
This PR exists is in conjunction with https://github.com/hysds/hysds/pull/103 and:
- updates the provisioning of the consolidated SDSWatch logstash configuration file
- adds and provisions the SDSWatch loggers for `systemd` and `supervisord` services
- updates the `sdswatch-dashboards.json` Kibana export with a minimal OPS UI
=> HC-338: initial implementation of OPS UI using SDSWatch and Kibana

sdscli/__init__.py, sdscli/adapters/hysds/fabfile.py
https://hysds-core.atlassian.net/browse/HC-348
i think i found a way to avoid using `cluster.py`
if `[tosca|figaro].js` is found in `~/.sds/files/` then it copies the files to `~/mozart/etc`
if not it instead copies `[tosca|figaro].template.js` to `~/mozart/etc`
also @pymonger what description/docstring should i add to `send_template_user_override` so future developers have a better understanding of it
=> Hc 348 - customizable tosca/figaro config in hysds_ui

sdscli/adapters/hysds/files/orch/grq/celeryconfig.py, sdscli/adapters/hysds/files/orch/metrics/celeryconfig.py, sdscli/adapters/hysds/files/orch/mozart/celeryconfig.py, sdscli/adapters/hysds/files/orch/verdi/celeryconfig.py
This PR updates the celeryconfig.py.tmpl template to include json as acceptable content, which is the format of broadcasted revoke payloads.
This was tested in NISAR using the NASA demo pipeline (dev-e2e + ALOS L0B processed to RSLC, GSLC and GCOV).
=> HC-380: accept json content to receive revokes

requirements.txt, sdscli/__init__.py, sdscli/adapters/hysds/update.py, sdscli/cloud/aws/asg.py
Details of this PR is shared with https://github.com/hysds/hysds/pull/128. 
Specific to this repository, this PR:
- add support to the sds CLI to allow end user to specify target tracking metric to use during `sds cloud asg create`
- detects target tracking metric per queue in `.sds/config` and specifies the corresponding CloudWatch metric name
- addresses an issue when running `sds update mozart` where the following error is encountered:
```
[100.104.10.132] out: ERROR: Exception:
[100.104.10.132] out: Traceback (most recent call last):
[100.104.10.132] out:   File "/export/home/hysdsops/verdi/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
[100.104.10.132] out:     status = run_func(*args)
[100.104.10.132] out:   File …
```
=> HC-393: add target tracking metric for autoscaling that allows for 1:1 scaling of jobs to workers

sdscli/adapters/hysds/fabfile.py
The sds CLI starts up the `supervisord` process on each PCM instance using a fabric's `run()` call. Currently when that happens, the spawned `supervisord` process also receives a `SIGHUP` which signals the `supervisord process to restart. For example, assume this sole process configured in `supervisord.conf` for mozart:
```
[program:instance_stats]
directory=/export/home/hysdsops/mozart/ops/hysds/scripts
command=/export/home/hysdsops/mozart/ops/hysds/scripts/log_instance_stats.py --interval 600
process_name=%(program_name)s
priority=1
numprocs=1
numprocs_start=0
redirect_stderr=true
stdout_logfile=%(here)s/../log/%(program_name)s.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
startsecs=10
```
When running `supervisord` manually, the log shows:
```
2021-12-02 00:06:05,045 INFO …
```
=> hotfix: SIGHUP being sent to supervisord process causing it to restart

requirements.txt, sdscli/__init__.py, setup.py
This PR updates the MarkupSafe and Jinja pins to support the updates to the latest Pallet Project versions (Flask 2.x).
=> HC-367: Update to support upgrade to latest Pallet Project versions

sdscli/__init__.py, setup.py
`fabric3` errors out running with this error when using python3.10:
```python
from collections import Mapping
``` 
it should not be:
```python
from collections.abc import Mapping
```
[`fab-classic`](https://pypi.org/project/fab-classic/) made a fix to that and also wrapped the fix in a `try/except` block for backwards compatibility: [their python 3.10 PR](https://github.com/ploxiln/fab-classic/pull/59/files#diff-d378f4c2286c57955479a7816c3d3f221e11d05b7215662542282eefed2c8f54)
`fabric/main.py`
```python
import inspect
from optparse import OptionParser
from importlib import import_module
try:
from collections.abc import Mapping
except ImportError:
from collections import Mapping
import six
```
@pymonger was able to test this out and confirmed that `sdscli` is working as normal after we …
=> move to fab-classic as it has active support and development

sdscli/adapters/hysds/fabfile.py, sdscli/adapters/hysds/files/event_status.template, sdscli/adapters/hysds/files/task_status.template, sdscli/adapters/hysds/files/worker_status.template
https://jira.jpl.nasa.gov/browse/NSDS-2584
related PR: https://github.com/hysds/hysds/pull/153
change(s):
- added `ilm_policy_mozart` lifecycle to `event`, `task` and `worker`
- added `*_status-current` alias to `event`, `task` and `worker`
- using `clean_indices_from_alias.py` script to clean indices by alias
=> NSDS-2584 - Implement rollover of old task, worker, event ES docs on Mozart ES

sdscli/__init__.py, sdscli/adapters/hysds/files/kibana_dashboard_import/job-dashboards.json, sdscli/adapters/hysds/files/kibana_dashboard_import/sdswatch-dashboards.json, sdscli/adapters/hysds/files/kibana_dashboard_import/worker-dashboards.json
This PR fixes an issue in the job metrics dashboard for the counts of generated products and inputs localized by jobs. It originally used a painless script to generate custom metrics for these but has been simplified to count up the job's `job.job_info.metrics.products_staged.id.keyword` and `job.job_info.metrics.inputs_localized.url.keyword`, respectively. 
Additionally, this PR updates the Kibana export JSON files for the dashboards (Job Metrics, Worker Metrics, Minimal OPS UI) for ELK 7.10.2.
=> hotfix: show product/input counts correctly

sdscli/__init__.py, sdscli/adapters/hysds/fabfile.py, sdscli/adapters/hysds/update.py
This PR resolves the issue where updating GRQ would break when a cluster is configured with AWS OpenSearch Service. This PR involved the following changes:
- Installing the base ES template using a python tool created in the following PRs:
- https://github.com/hysds/mozart/pull/49
- https://github.com/hysds/grq2/pull/59
- This python tool allows us to properly install the base templates whether the cluster is configured with local GRQ or AWS OpenSearch.
- Made the following updates to the mozart update function:
- Make sure to push the celery config out first before calling the install base ES template tool as that tool relies on the existence of the celeryconfig.py in order for that tool to run properly.
- Made the following updates to the grq update function:
-   Make sure to push out …
=> HC-469: Cannot properly update GRQ when cluster is configured with AWS OpenSearch Service

sdscli/__init__.py, sdscli/adapters/hysds/fabfile.py, sdscli/adapters/hysds/status.py
- Updated the installation of the Mozart ILM policy and templates such that they call a script now instead of the localhost:9200 endpoint.
- Regarding installation of the templates, updated the existing `install_es_template.sh` in order to do this. See mozart repo PR for more details: https://github.com/hysds/mozart/pull/53
- Also modified the `sds status` command such that when we display the ElasticSearch status, we ping the actual server by relying on the IP set in the sds config as opposed to simply relying on `systemctl status elasticsearch`, which always assumes that Elasticsearch is running on the host machine.
=> HC-496: Updates to optionally support a separate Mozart ES cluster deployment

sdscli/adapters/hysds/files/opensearch_ism_policy_mozart.json
This hot fix updates the ISM Mozart policy such that the index pattern is set correctly in order to attach the ISM Mozart policy to those job related status indices that get created daily:
- event_status*
- task_status*
- worker_status*
- job_status*
=> hot-fix: Fix the index pattern in the ISM Mozart policy

sdscli/__init__.py, sdscli/adapters/hysds/pkg.py
Ticket: https://hysds-core.atlassian.net/browse/HC-517
Add support in sdscli for container specifications which do not specify a container_url and only specify a container_name. This behavior is already supported within hysds-core and only requires a tooling change to the sds pkg import command.
https://github.com/hysds/hysds/blob/944d3a89997b1aff416dc627b095a6b5e10b2242/hysds/containers/base.py#L279-L283 
Additionally, add support for importing user rules from a package if part of the package.
=> Enable importing of container name-only images and user-rules via sdscli

sdscli/__init__.py, sdscli/adapters/hysds/files/install.sh, sdscli/adapters/hysds/files/supervisord.conf.tmpl, sdscli/adapters/hysds/update.py
This PR makes the following updates related to supporting the use of podman within HySDS Core:
- The sds update commands were updated to render the new `run_verdi_podman.sh` script template and to deploy it out to verdi. This script is responsible for starting up verdi under podman
- Updated the install.sh and the supervisord.conf.tmpl to render the 2 new variables that are needed in order to properly run Verdi in podman:
- HOST_VERDI_HOME - The path to the base directory where the verdi code resides on the host.
- HOST_USER - The name of the user on the host, which will invoke the podman commands
See these related PRs for additional info:
- https://github.com/hysds/hysds/pull/189
- https://github.com/hysds/hysds-dockerfiles/pull/11
=> HC-522: Updates to support deployment of Verdi to run with Podman

sdscli/adapters/hysds/files/job_status.template
This PR is in conjunction with the following:
- hysds: https://github.com/hysds/hysds/pull/193
- lightweight jobs: https://github.com/hysds/lightweight-jobs/pull/34
This PR updates the existing job_status template such that it adds the `job_failed` index.
**Test**
See comments in https://hysds-core.atlassian.net/browse/HC-546
=> HC-546: Add job_failed index to job_status template

sdscli/__init__.py, sdscli/adapters/hysds/files/install.sh, sdscli/adapters/hysds/files/supervisord.conf.tmpl
This PR makes some updates that support moving away from the default OPS user in the Verdi container. These updates are also driven by further testing that was done with Podman in the HECC environment.
- Made install.sh more modular in that it uses `HOST_VERDI_HOME` instead of `HOME` to make the script support the use case of being able to deploy the PCM code bundle anywhere instead of always assuming it will be under $HOME
- Similiarly, `DATA_DIR` was introduced to be able to make it more modular to reference the base working directory to be anywhere instead of assuming `/data` always.
- Use `cp` instead of `mv` when deploying the AWS, .netrc, and .boto files/directories.
- supervisord.conf.tmpl was updated such that it no longer has the httpd service as a default due to JPL security in …
=> HC-522-update: Updates that support moving away from default OPS user in the Verdi container
